{{- if .Values.sealed.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealed.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
{{- range $key, $value := .Values.sealed.data }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
